steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${_IMAGE}",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${_IMAGE}"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - ${__SERVICE_NAME}
      - --image
      - $LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${_IMAGE}
      - --platform
      - managed
      - --region
      - $LOCATION
      - --allow-unauthenticated
      - --set-secrets
      - MICROCMS_SERVICE_DOMAIN=MICROCMS_SERVICE_DOMAIN:latest
      - --set-secrets
      - MICROCMS_API_KEY=MICROCMS_API_KEY:latest
substitutions:
  _IMAGE: my-image
timeout: 1200s
