import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/[lang]/globals.css";
import type { Language } from "@/types/language";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params: { lang },
  children,
}: Readonly<{
  params: { lang: Language };
  children: React.ReactNode;
}>) {
  return (
    <html lang={lang}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
